### PR TITLE
Fix basic completion

### PR DESCRIPTION
**Pull request by lbenc135**
Hi, I've been playing a bit with this repo and wanted to show you what I came up with.

Basically I added the grammar for Java (`then` part), refactored a few things to work with it, and fixed some bugs. You can try it in VSCode, it now suggests the correct keywords in the appropriate places.

I'm not sure what your vision is for this project, but I would love to hear it and contribute what I can. Feel free to close this PR if this is not what you envisioned.

### CODE REVIEW

**Comment by mariofusco** [comment]
@lbenc135 Thanks a lot for your contribution. I'll check and merge it asap. Would you be interested in participating to a Google Summer of Code related to this? https://spaces.redhat.com/display/GSOC/Google+Summer+of+Code+2022+Ideas#GoogleSummerofCode2022Ideas-Drools%E2%80%93Antlr4basedDRLparser

**Comment by lbenc135** [comment]
@mariofusco I'm afraid I can work only part-time on this since I have a full-time job. However, I would like to be involved and I can join remotely periodically.

Btw, I'm also working on the error checking functionality, so I may submit another PR soon. If you have the time, it would be great if we could have a quick call to coordinate a bit.

**Comment by evacchi** [comment]
sure @mariofusco I am on board 🚀  thanks for the contribution @lbenc135

**Comment by lbenc135** [comment]
Great! I'll send you an invite for the meeting @mariofusco @evacchi.

**Pull request merged**
